### ISSUE TITLE
Incomplete Tuner scripts

### ISSUE THREAD

**Issue by Taardisaa** [purseclab/D-helix#2]
Hi,
I am debugging regenerated_inall.py, and it seems that some of the java scripts are missing:

ghidra_decompiled_java_script3 = "Decompile_pre.java"
ghidra_decompiled_java_script4 = "Decompile_pre_base.java"

I looked at the folder "ghidra_scripts" and only found "Decompile.java", "Decompilehtml.java" and other scripts.

Thanks.

**Comment by Muqi-Zou** [comment]
Sorry for missing these two scripts, they have been uploaded in ghidra_scripts.
